import React from 'react';
import { useParams, Link } from 'react-router-dom';
import PageHero from '../components/PageHero';
import FadingVideo from '../components/FadingVideo';
import { motion } from 'motion/react';
import { 
  Bot, Mail, MessageSquare, PhoneCall, Globe2, Code2, 
  CheckCircle2, ArrowRight, Star, BarChart3, ShieldCheck, Zap
} from 'lucide-react';

const serviceData: { [key: string]: any } = {
  'chatbots': {
    title: 'AI Chatbots',
    badge: 'Autonomous Engagement',
    video: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260422_191657_800d4e1f-7ab3-41af-90b6-9bd3039eb294.mp4",
    icon: <MessageSquare className="w-12 h-12" />,
    description: "Intelligent web agents that represent your brand 24/7. Not simple menu buttons, but context-aware AI built to qualify leads instantly.",
    longDescription: "Our AI Chatbots leverage Natural Language Processing (NLP) to understand customer intent. Unlike traditional bots that frustrate users with rigid menus, our systems hold fluid conversations, answer complex FAQs, and book appointments directly into your CRM.",
    features: [
      { title: "24/7 Lead Qualificaiton", text: "Never let a weekend lead go cold. Our bots qualify prospects based on your specific criteria." },
      { title: "Seamless CRM Integration", text: "Instant data sync with GoHighLevel, HubSpot, Salesforce, and more." },
      { title: "Multi-Channel Logic", text: "Deploy the same brain across your website, Facebook, and Instagram." }
    ]
  },
  'whatsapp': {
    title: 'WhatsApp Automation',
    badge: 'Direct-to-Customer',
    video: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260418_115655_b4d9cd77-feed-43cd-a198-af78ebdf1f7a.mp4",
    icon: <Mail className="w-12 h-12" />,
    description: "Official WhatsApp Cloud API solutions that land directly in your customer's pocket with 98% open rates.",
    longDescription: "We engineer mass broadcasting and automated drip sequences that feel personal. From abandoned cart recovery to re-engagement campaigns, we build the logic that handles the heavy lifting of sales follow-ups.",
    features: [
      { title: "Broadcast Campaigns", text: "Send thousands of personalized messages without the risk of being blocked." },
      { title: "Drip Follow-ups", text: "Automated sequences that nurture leads from first touch to closed sale." },
      { title: "Verified Business Status", text: "Complete setup for the green tick and official API access." }
    ]
  },
  'voice': {
    title: 'AI Voice Agents',
    badge: 'The Digital Receptionist',
    video: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260411_104032_69319010-2458-492b-b04d-b40a5dfa4482.mp4",
    icon: <PhoneCall className="w-12 h-12" />,
    description: "Human-like voice bots that handle calls, qualify prospects, and route hot leads. Zero fatigue, 100% precision.",
    longDescription: "Our AI Voice Agents are designed for high-volume environments like clinics, real estate, and law firms. They handle inbound inquiries with sub-500ms latency, making them indistinguishable from human receptionists while maintaining perfect accuracy.",
    features: [
      { title: "Smart Escalation", text: "Transfer urgent high-value leads to live agents instantly based on sentiment." },
      { title: "Call Recording & Analysis", text: "Every interaction is transcribed and analyzed for conversion data." },
      { title: "Calendar Sync", text: "Direct booking for dental clinics, law firms, and consulting offices." }
    ]
  },
  'websites': {
    title: 'High-Performance Websites',
    badge: 'Conversion Engineering',
    video: "https://stream.mux.com/r6pXRAJb3005XEEbl1hYU1x01RFJDSn7KQApwNGgAHHbU.m3u8",
    icon: <Globe2 className="w-12 h-12" />,
    description: "Website engineering focused on one goal: Conversion. Every pixel is placed to turn visitors into buyers.",
    longDescription: "We don't build generic 'About Us' websites. We build conversion machines. Using high-speed architectures, AI-driven copywriting, and precision UX, we create digital systems that guide anonymous traffic through a pre-designed psychological path to a sale.",
    features: [
      { title: "Conversion Architecture", text: "Layouts designed around the 'Lead Hook' to maximize capture rates." },
      { title: "AI Copywriting", text: "Sales copy generated by models trained on 10,000+ top-performing landing pages." },
      { title: "Speed & SEO Optimized", text: "Lightning-fast load times that lower bounce rates and improve Google rankings." }
    ]
  },
  'seo': {
    title: 'AI-Powered SEO',
    badge: 'Search Dominance',
    video: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260306_074215_04640ca7-042c-45d6-bb56-58b1e8a42489.mp4",
    icon: <Bot className="w-12 h-12" />,
    description: "Rank for high-intent keywords on autopilot using LLM-driven semantic clusters.",
    longDescription: "Manual content production is slow and expensive. We deploy AI content engines that produce high-authority, human-passing blog posts and articles scheduled for consistent ranking dominance.",
    features: [
      { title: "Semantic Clustering", text: "Map entire topical domains to establish search authority fast." },
      { title: "Dynamic Keyword Injection", text: "AI that adapts to changing search trends and competitor gaps." },
      { title: "Automated Content Sprints", text: "Publish 30+ high-quality articles per month without hiring a team." }
    ]
  },
  'social': {
    title: 'Social Media Mastery',
    badge: 'Brand Authority',
    video: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260314_131748_f2ca2a28-fed7-44c8-b9a9-bd9acdd5ec31.mp4",
    icon: <Globe2 className="w-12 h-12" />,
    description: "Autonomous content curation and engagement engines for LinkedIn, Twitter, and Instagram.",
    longDescription: "Stay relevant 24/7. Our systems curate trending topics in your niche, generate brand-aligned posts, and schedule them across all platforms to maintain constant presence and trust.",
    features: [
      { title: "Trend Analysis AI", text: "Spot viral opportunities in your industry before they peak." },
      { title: "Engagement automation", text: "Smart replies to comments to boost algorithm favorability." },
      { title: "Visual Generation", text: "AI-created assets that match your brand's unique aesthetic." }
    ]
  },
  'video': {
    title: 'Short-Form Production',
    badge: 'Viral Hook Engine',
    video: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260324_024928_1efd0b0d-6c02-45a8-8847-1030900c4f63.mp4",
    icon: <Code2 className="w-12 h-12" />,
    description: "Turning raw footage into high-impact Reels and Shorts using AI-enhanced editing workflows.",
    longDescription: "We use machine learning to identify high-retention hooks in your long-form videos, automatically generating captions, adding dynamic zoom-ins, and optimizing for the TikTok/Reels algorithms.",
    features: [
      { title: "AI Subtitle Engine", text: "Perfect captions with dynamic highlights for maximum retention." },
      { title: "Automatic Hook Extraction", text: "The first 3 seconds are everything. We optimize them for curiosity." },
      { title: "Platform-Specific Sizing", text: "One long video turns into 10 multi-platform assets instantly." }
    ]
  }
};

export default function ServiceDetail() {
  const { id } = useParams();
  const service = serviceData[id || 'websites'];

  if (!service) return <div className="text-white text-center py-20">Service Not Found</div>;

  return (
    <div className="bg-black text-white min-h-screen">
      <PageHero 
        title={service.title}
        subtitle={service.description}
        videoSrc={service.video}
        badge={service.badge}
      />

      {/* Main Content Grid */}
      <section className="py-24 px-8 md:px-16 lg:px-20 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-20">
          
          {/* Detailed Info */}
          <div className="lg:col-span-2 space-y-12">
            <div className="space-y-6">
              <h2 className="text-4xl font-heading italic tracking-tight">The {service.title} Blueprint</h2>
              <p className="text-white/60 font-body text-lg leading-relaxed font-light">
                {service.longDescription}
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {service.features.map((f: any, i: number) => (
                <motion.div 
                  key={f.title}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                  className="liquid-glass p-8 rounded-[2rem] border border-white/5 space-y-4"
                >
                  <CheckCircle2 className="w-6 h-6 text-white/40" />
                  <h3 className="text-xl font-heading italic">{f.title}</h3>
                  <p className="text-sm text-white/50 font-body font-light leading-relaxed">{f.text}</p>
                </motion.div>
              ))}
            </div>

            {/* Technical Specs Section */}
            <div className="space-y-8 py-12 border-y border-white/5">
               <h3 className="text-2xl font-heading italic text-white">Technical Infrastructure</h3>
               <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  {[
                    { l: "Latency", v: "<500ms" },
                    { l: "Uptime", v: "99.99%" },
                    { l: "Security", v: "AES-256" },
                    { l: "Scaling", v: "Elastic" }
                  ].map((s, i) => (
                    <div key={i} className="p-4 rounded-2xl bg-white/[0.02] border border-white/5">
                      <div className="text-[10px] uppercase tracking-widest text-white/30 mb-1">{s.l}</div>
                      <div className="text-lg font-heading italic text-white">{s.v}</div>
                    </div>
                  ))}
               </div>
            </div>

            {/* Why WebCat Labs */}
            <div className="liquid-glass-strong p-10 rounded-[2.5rem] border border-white/5 bg-white/[0.01]">
              <h3 className="text-2xl font-heading italic mb-8 flex items-center gap-3">
                <BarChart3 className="w-6 h-6 text-white/60" /> Why WebCat Labs Engineering?
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div className="space-y-2">
                  <span className="text-white font-semibold">10x ROI Focus</span>
                  <p className="text-xs text-white/40 font-body">Every line of code is written to drive measurable profit.</p>
                </div>
                <div className="space-y-2">
                  <span className="text-white font-semibold">Enterprise Security</span>
                  <p className="text-xs text-white/40 font-body">Your data is yours. We use official APIs and secure logic.</p>
                </div>
                <div className="space-y-2">
                  <span className="text-white font-semibold">Native Support</span>
                  <p className="text-xs text-white/40 font-body">24/7 engineering support as your AI system scales.</p>
                </div>
              </div>
            </div>

            {/* Engineered Implementation Process */}
            <div className="py-12 space-y-12">
               <h3 className="text-3xl font-heading italic text-white text-center">Engineered Implementation</h3>
               <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                  {[
                    { step: "01", title: "Structural Audit", desc: "We analyze your current digital footprint and identify conversion leaks." },
                    { step: "02", title: "AI Injection", desc: "Custom neural models are trained on your business data and brand voice." },
                    { step: "03", title: "Live Scaling", desc: "The system is deployed and monitored 24/7 for conversion optimization." }
                  ].map((item, i) => (
                    <motion.div 
                      key={i}
                      initial={{ opacity: 0, y: 20 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: i * 0.1 }}
                      className="relative p-8 rounded-[2rem] bg-white/[0.02] border border-white/5 group hover:border-white/10 transition-colors"
                    >
                      <div className="text-4xl font-heading italic text-white/10 absolute top-4 right-8">{item.step}</div>
                      <h4 className="text-xl font-heading italic text-white mb-4">{item.title}</h4>
                      <p className="text-sm text-white/40 font-body font-light leading-relaxed">{item.desc}</p>
                    </motion.div>
                  ))}
               </div>
            </div>
          </div>

          {/* Sidebar CTA */}
          <div className="space-y-8">
            <div className="liquid-glass p-8 rounded-[2.5rem] sticky top-32 border border-white/5">
              <div className="p-4 rounded-2xl bg-white/5 w-fit mb-6">
                {service.icon}
              </div>
              <h3 className="text-2xl font-heading italic mb-4">Start your {service.title} transformation</h3>
              <p className="text-sm text-white/50 font-body font-light leading-relaxed mb-8">
                Average deployment time for this system is 14 days. Book a free audit to see how it fits your business workflow.
              </p>
              <Link to="/contact" className="w-full bg-white text-black py-4 rounded-full font-semibold flex items-center justify-center gap-2 hover:bg-white/90 transition-all">
                Book Free Audit
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>

        </div>
      </section>

      {/* Testimonial Section for Specific Service */}
      <section className="py-32 bg-white/5 border-y border-white/5 text-center px-8 relative overflow-hidden">
        <FadingVideo 
          src="https://stream.mux.com/Si6ej2ZRrxRCnTYBXSScDRCdd7CGnyTqiPszZcw3z4I.m3u8"
          className="absolute inset-0 w-full h-full object-cover opacity-40"
        />
        <div className="max-w-3xl mx-auto space-y-8 relative z-10">
          <div className="flex justify-center gap-1">
             {[1,2,3,4,5].map(i => <Star key={i} className="w-4 h-4 fill-white text-white" />)}
          </div>
          <h2 className="text-3xl md:text-5xl font-heading italic text-white">
            "The {service.title} system WebCat Labs built tripled our engagement in less than a month."
          </h2>
          <div>
            <p className="text-white font-medium">Verified Partner</p>
            <p className="text-[10px] text-white/30 uppercase tracking-widest mt-1">Industrial Scaling Sector</p>
          </div>
        </div>
      </section>
    </div>
  );
}
